spring:
  datasource:
    url: jdbc:mysql://soloproject.ctgziet2cuq2.ap-northeast-2.rds.amazonaws.com:3306/sys
    username: admin
    password: ba619161
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      
mybatis:
  mapper-locations:
  - /mappers/*.xml
