spring:
  datasource:
    url: jdbc:mysql://admin.ctgziet2cuq2.ap-northeast-2.rds.amazonaws.com:3306/solo_project
    username: admin
    password: ba619161
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      
mybatis:
  mapper-locations:
  - /mappers/*.xml


jwt:
  secret: Hf0MLSCnB5M6gtjcHmokIxABqjplbHtRypoN8H2vMTxVOHf0MjcHmokIxABqjplbHtRypoN8H2vMTxVO
  